plugins {
    id 'java-library'
}

group = mod_group_id
version = mod_version

subprojects {
    repositories {
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Sponge'
                    url = 'https://repo.spongepowered.org/repository/maven-public'
                }
            }
            filter { includeGroup('org.spongepowered') }
        }
        exclusiveContent {
            forRepositories(
                    maven {
                        name = 'ParchmentMC'
                        url = 'https://maven.parchmentmc.org/'
                    },
                    maven {
                        name = 'NeoForge'
                        url = 'https://maven.neoforged.net/releases'
                    }
            )
            filter { includeGroup('org.parchmentmc.data') }
        }
        maven {
            name = 'BlameJared'
            url = 'https://maven.blamejared.com'
        }
    }

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(java_version))
    }

    base {
        archivesName = "${mod_name}-${minecraft_version}-${mod_version}-${project.name}"
    }
}
