buildscript {
    repositories {
        // These repositories are only for Gradle plugins, put any other repositories in the repository block further below
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7.38'
    }
}

plugins {
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'idea'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

apply plugin: 'org.spongepowered.mixin'

base {
    archivesName = "${mod_name}-${project.name}-${minecraft_version}-${mod_version}"
}

minecraft {
    mappings channel: "parchment", version: "${parchment_version}-${parchment_minecraft}"

    copyIdeResources.set(true)

    runs {
        // applies to all the run configs below
        configureEach {
/*            mods{
                "${mod_id}" {
                    source(sourceSets.main)
                    //source(project(":common").sourceSets.main)
                }
            }*/

            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            property 'forge.logging.markers', 'REGISTRIES'


            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            property 'forge.logging.console.level', 'debug'
        }

        client {
            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            property 'forge.enabledGameTestNamespaces', mod_id

            arg "-Dnet.minecraftforge.gradle.check.certs=false"
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            // example of overriding the workingDirectory set in configureEach above
            workingDirectory project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.experimental.mixins.json")
}

// Include resources generated by data generators.
sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

repositories {
    maven { url = 'https://maven.parchmentmc.org' }
    mavenCentral()
    maven {
        // location of the maven that hosts JEI files before January 2023
        name = "Progwml6's maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        // Add curse maven to repositories
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
/*    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }*/
    maven {
        name = "Cloth Config"
        url = uri("https://maven.shedaniel.me/")
    }
}

dependencies {
    compileOnly project(":common")

    implementation 'org.jetbrains:annotations:24.0.1'

    annotationProcessor("org.spongepowered:mixin:0.8.7:processor")

    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    //1.21.4 jei hove no forge version

    //NOTE: curios has no more forge version

    //implementation fg.deobf("me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}")

    // Hack fix for now, force jopt-simple to be exactly 5.0.4 because Mojang ships that version, but some transtive dependencies request 6.0+
    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }
}

processResources {
    var replaceProperties = [
            'version'                      : mod_version,
            'group'                        : project.group, //Else we target the task's group.
            'minecraft_version'            : minecraft_version,
            'minecraft_version_range'      : minecraft_version_range,
            'fabric_version'               : fabric_version,
            'fabric_loader_version'        : fabric_loader_version,
            'mod_name'                     : mod_name,
            'mod_author'                   : mod_authors,
            'mod_id'                       : mod_id,
            'license'                      : mod_license,
            'description'                  : mod_description,
            "forge_version"                : forge_version,
            "forge_loader_version_range"   : forge_loader_version_range,
            'credits'                      : credits,
            'java_version'                 : java_version
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }

    from project(':common').sourceSets.main.resources
}

compileJava {
    source(project(':common').sourceSets.main.allSource)
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    finalizedBy('reobfJar')
    from(project(':common').sourceSets.main.output)
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.experimental.mixins.json"
    ])
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// Merge the resources and classes into the same directory.
// This is done because java expects modules to be in a single directory.
// And if we have it in multiple we have to do performance intensive hacks like having the UnionFileSystem
// This will eventually be migrated to ForgeGradle so modders don't need to manually do it. But that is later.
sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}


//gradle.taskGraph.whenReady { graph ->
//    // If running the client or server in development, merge resources with classes
//    if (graph.hasTask(":runClient") || graph.hasTask(":runServer")) {
//        sourceSets.main.output.resourcesDir = file("$buildDir/classes/java/main")
//    }
//}
