plugins {
    id 'net.neoforged.moddev.legacyforge' version '2.0.77'
    id 'idea'
}

base {
    archivesName = "${mod_name}-${minecraft_version}-${mod_version}-${project.name}"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
}

configurations {
    commonJava{
        canBeResolved = true
    }
    commonResources{
        canBeResolved = true
    }
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = false

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        modPack{
            client()
            programArguments.addAll '--username','nep'
            gameDirectory = file('runModpack')
        }
        data {
            data()
            programArguments.addAll '--mod', mod_id as String, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()


        }
        /*configureEach {
            jvmArg '--add-opens=java.base/java.lang.ref=ALL-UNNAMED'
        }*/
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

repositories {
    maven {
        // location of the maven that hosts JEI files before January 2023
        name = "Progwml6's maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        // Add curse maven to repositories
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    implementation project(":common")

    implementation 'org.jetbrains:annotations:24.0.1'

    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')

    annotationProcessor("org.spongepowered:mixin:0.8.7:processor")

    //modpack
    //def f = files('libs/tacz-1.20.1-1.1.4-hotfix-all.jar')
    //runtimeOnly f

    //runtimeOnly("curse.maven:timeless-and-classics-zero-1028108:6632240-sources-6633203")
}

dependencies {
    /* other minecraft dependencies are here */
    compileOnly("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    // compile against the JEI API but do not include it at runtime
    modCompileOnly("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    // at runtime, use the full JEI jar for Forge
    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}
processResources {
    var expandProps = [
            'version'                      : mod_version,
            'group'                        : project.group, //Else we target the task's group.
            'minecraft_version'            : minecraft_version,
            'minecraft_version_range'      : minecraft_version_range,
            'fabric_version'               : fabric_version,
            'fabric_loader_version'        : fabric_loader_version,
            'mod_name'                     : mod_name,
            'mod_author'                   : mod_authors,
            'mod_id'                       : mod_id,
            'license'                      : mod_license,
            'description'                  : mod_description,
            "forge_version"                     :        forge_version,
            "forge_loader_version_range": forge_loader_version_range,
            'credits'                      : credits,
            'java_version'                 : java_version
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}


jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}
