//todo compare with multi-loader's common build
plugins {
    id 'net.neoforged.moddev.legacyforge' version '2.0.77'
    id 'idea'
}

legacyForge {
    mcpVersion = minecraft_version

    validateAccessTransformers = false
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at)
    }
    /*if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }*/

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'org.jetbrains:annotations:24.0.1'

    implementation "org.spongepowered:mixin:0.8.7"
    annotationProcessor "org.spongepowered:mixin:0.8.7:processor"
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

test {
    useJUnitPlatform()
}

jar {
    archiveBaseName.set("common")
    from sourceSets.main.output
}
